import type { NodeDefinition } from "./types.js";

export const triggers: NodeDefinition[] = [
  {
    id: "x-post",
    name: "X Post",
    description: "Triggers when a new post matches your criteria on X (Twitter)",
    icon: "\u{1D54F}",
    color: "#1DA1F2",
    category: "off-chain",
    role: "trigger",
    outputs: [
      { key: "postId", label: "Post ID", type: "string" },
      { key: "username", label: "Username", type: "string" },
      { key: "text", label: "Text", type: "string" },
      { key: "timestamp", label: "Timestamp", type: "string" },
    ],
    configFields: [
      { key: "username", label: "Username", type: "text", placeholder: "@handle", required: true },
      { key: "includeRetweets", label: "Include Retweets", type: "toggle", defaultValue: false },
      { key: "keywords", label: "Keywords", type: "text", placeholder: "comma-separated keywords" },
    ],
  },
  {
    id: "balance",
    name: "Balance Monitor",
    description: "Triggers when a wallet balance crosses a threshold",
    icon: "\uD83D\uDCB0",
    color: "#F59E0B",
    category: "on-chain",
    role: "trigger",
    outputs: [
      { key: "address", label: "Address", type: "string" },
      { key: "balance", label: "Balance", type: "number" },
      { key: "token", label: "Token", type: "string" },
      { key: "triggered", label: "Triggered", type: "boolean" },
    ],
    configFields: [
      { key: "address", label: "Wallet Address", type: "text", placeholder: "0x...", required: true },
      { key: "token", label: "Token", type: "text", placeholder: "ETH, USDC, ..." },
      { key: "threshold", label: "Threshold", type: "number", placeholder: "0" },
    ],
  },
  {
    id: "every-period",
    name: "Every Period",
    description: "Triggers on a recurring schedule",
    icon: "\u23F0",
    color: "#8B5CF6",
    category: "off-chain",
    role: "trigger",
    outputs: [
      { key: "interval", label: "Interval", type: "number" },
      { key: "unit", label: "Unit", type: "string" },
      { key: "triggeredAt", label: "Triggered At", type: "string" },
    ],
    configFields: [
      { key: "interval", label: "Interval", type: "number", placeholder: "1", required: true, defaultValue: 1 },
      {
        key: "unit",
        label: "Unit",
        type: "select",
        options: [
          { label: "Minutes", value: "minutes" },
          { label: "Hours", value: "hours" },
          { label: "Days", value: "days" },
        ],
        defaultValue: "hours",
      },
    ],
  },
  {
    id: "price-alert",
    name: "Price Alert",
    description: "Triggers when a token price crosses a level",
    icon: "\uD83D\uDCC8",
    color: "#10B981",
    category: "on-chain",
    role: "trigger",
    outputs: [
      { key: "token", label: "Token", type: "string" },
      { key: "currentPrice", label: "Current Price", type: "number" },
      { key: "targetPrice", label: "Target Price", type: "number" },
      { key: "direction", label: "Direction", type: "string" },
      { key: "triggered", label: "Triggered", type: "boolean" },
    ],
    configFields: [
      { key: "token", label: "Token", type: "text", placeholder: "ETH", required: true },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Above", value: "above" },
          { label: "Below", value: "below" },
        ],
        defaultValue: "above",
      },
      { key: "price", label: "Price (USD)", type: "number", placeholder: "0" },
    ],
  },
  {
    id: "new-block",
    name: "New Block",
    description: "Triggers on every new block on the selected chain",
    icon: "\u26D3\uFE0F",
    color: "#6366F1",
    category: "on-chain",
    role: "trigger",
    outputs: [
      { key: "chain", label: "Chain", type: "string" },
      { key: "blockNumber", label: "Block Number", type: "number" },
      { key: "blockHash", label: "Block Hash", type: "string" },
      { key: "timestamp", label: "Timestamp", type: "string" },
    ],
    configFields: [
      {
        key: "chain",
        label: "Chain",
        type: "select",
        options: [
          { label: "Ethereum", value: "ethereum" },
          { label: "Polygon", value: "polygon" },
          { label: "Arbitrum", value: "arbitrum" },
        ],
        defaultValue: "ethereum",
      },
    ],
  },
  {
    id: "webhook",
    name: "Webhook",
    description: "Triggers when an HTTP POST is received at your webhook URL",
    icon: "\uD83D\uDD17",
    color: "#EC4899",
    category: "off-chain",
    role: "trigger",
    outputs: [
      { key: "path", label: "Path", type: "string" },
      { key: "payload", label: "Payload", type: "object" },
      { key: "receivedAt", label: "Received At", type: "string" },
    ],
    configFields: [
      { key: "path", label: "Path", type: "text", placeholder: "auto-generated" },
      { key: "secret", label: "Secret", type: "text", placeholder: "auto-generated" },
    ],
  },
  {
    id: "polymarket",
    name: "Polymarket",
    description: "Triggers when a prediction market reaches a price threshold",
    icon: "\uD83D\uDCC0",
    color: "#0052FF",
    category: "off-chain",
    role: "trigger",
    outputs: [
      { key: "question", label: "Question", type: "string" },
      { key: "outcome", label: "Outcome", type: "string" },
      { key: "currentPrice", label: "Current Price", type: "number" },
      { key: "threshold", label: "Threshold", type: "number" },
      { key: "direction", label: "Direction", type: "string" },
      { key: "marketUrl", label: "Market URL", type: "string" },
    ],
    configFields: [
      { key: "marketId", label: "Market", type: "text", placeholder: "Search and select a market...", required: true },
      { key: "marketQuestion", label: "Market Question", type: "text", placeholder: "Selected market question" },
      {
        key: "outcome",
        label: "Outcome",
        type: "select",
        options: [
          { label: "Yes", value: "Yes" },
          { label: "No", value: "No" },
        ],
        defaultValue: "Yes",
      },
      { key: "threshold", label: "Threshold (%)", type: "number", placeholder: "65" },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Above", value: "above" },
          { label: "Below", value: "below" },
        ],
        defaultValue: "above",
      },
    ],
  },
];

export const actions: NodeDefinition[] = [
  {
    id: "swap",
    name: "Swap Token",
    description: "Swap one token for another via a DEX",
    icon: "\uD83D\uDD04",
    color: "#3B82F6",
    category: "on-chain",
    role: "action",
    outputs: [
      { key: "amountIn", label: "Amount In", type: "number" },
      { key: "amountOut", label: "Amount Out", type: "number" },
      { key: "txHash", label: "Tx Hash", type: "string" },
      { key: "status", label: "Status", type: "string" },
    ],
    configFields: [
      { key: "fromToken", label: "From Token", type: "wallet-token-select", required: true },
      { key: "fromTokenName", label: "From Token Name", type: "text" },
      { key: "toToken", label: "To Token", type: "token-search", required: true },
      { key: "toTokenName", label: "To Token Name", type: "text" },
      { key: "amount", label: "Amount", type: "number", placeholder: "0" },
      { key: "slippage", label: "Slippage %", type: "number", placeholder: "0.5", defaultValue: 0.5 },
    ],
  },
  {
    id: "send-tx",
    name: "Send Transaction",
    description: "Send a raw transaction on-chain",
    icon: "\uD83D\uDCE4",
    color: "#F97316",
    category: "on-chain",
    role: "action",
    outputs: [
      { key: "txHash", label: "Tx Hash", type: "string" },
      { key: "blockNumber", label: "Block Number", type: "number" },
      { key: "status", label: "Status", type: "string" },
    ],
    configFields: [
      { key: "to", label: "To Address", type: "text", placeholder: "0x...", required: true },
      { key: "value", label: "Value (ETH)", type: "number", placeholder: "0" },
      { key: "data", label: "Data (hex)", type: "textarea", placeholder: "0x" },
    ],
  },
  {
    id: "notification",
    name: "Notification",
    description: "Send a notification via email, push, or Discord",
    icon: "\uD83D\uDD14",
    color: "#EAB308",
    category: "off-chain",
    role: "action",
    outputs: [
      { key: "channel", label: "Channel", type: "string" },
      { key: "sentAt", label: "Sent At", type: "string" },
      { key: "status", label: "Status", type: "string" },
    ],
    configFields: [
      {
        key: "channel",
        label: "Channel",
        type: "select",
        options: [
          { label: "Email", value: "email" },
          { label: "Push", value: "push" },
          { label: "Discord", value: "discord" },
        ],
        defaultValue: "email",
      },
      { key: "message", label: "Message", type: "textarea", placeholder: "Your message here", required: true },
    ],
  },
  {
    id: "api-call",
    name: "API Call",
    description: "Make an HTTP request to any external API",
    icon: "\uD83C\uDF10",
    color: "#06B6D4",
    category: "off-chain",
    role: "action",
    outputs: [
      { key: "statusCode", label: "Status Code", type: "number" },
      { key: "body", label: "Response Body", type: "object" },
    ],
    configFields: [
      { key: "url", label: "URL", type: "text", placeholder: "https://...", required: true },
      {
        key: "method",
        label: "Method",
        type: "select",
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "DELETE", value: "DELETE" },
        ],
        defaultValue: "GET",
      },
      { key: "headers", label: "Headers (JSON)", type: "textarea", placeholder: '{"Content-Type": "application/json"}' },
      { key: "body", label: "Body (JSON)", type: "textarea", placeholder: "{}" },
    ],
  },
  {
    id: "condition",
    name: "Condition",
    description: "Branch workflow execution based on a condition",
    icon: "\uD83D\uDD00",
    color: "#A855F7",
    category: "off-chain",
    role: "action",
    outputs: [
      { key: "result", label: "Result", type: "boolean" },
      { key: "actual", label: "Actual Value", type: "string" },
    ],
    configFields: [
      { key: "field", label: "Field", type: "text", placeholder: "data.value" },
      {
        key: "operator",
        label: "Operator",
        type: "select",
        options: [
          { label: ">", value: ">" },
          { label: "<", value: "<" },
          { label: "==", value: "==" },
          { label: "!=", value: "!=" },
          { label: "contains", value: "contains" },
        ],
        defaultValue: "==",
      },
      { key: "value", label: "Value", type: "text", placeholder: "compare value" },
    ],
  },
  {
    id: "log",
    name: "Log Output",
    description: "Echoes its resolved message — useful for testing expression resolution",
    icon: "\uD83D\uDCCB",
    color: "#6B7280",
    category: "off-chain",
    role: "action",
    outputs: [
      { key: "message", label: "Message", type: "string" },
      { key: "timestamp", label: "Timestamp", type: "string" },
    ],
    configFields: [
      { key: "message", label: "Message", type: "textarea", placeholder: "Use { } to reference upstream output", required: true },
    ],
  },
  {
    id: "sentiment",
    name: "Sentiment Analysis",
    description: "Analyzes text and returns a sentiment score from 0 (negative) to 1 (positive)",
    icon: "\uD83E\uDDE0",
    color: "#EC4899",
    category: "off-chain",
    role: "action",
    outputs: [
      { key: "score", label: "Score (0-1)", type: "number" },
      { key: "label", label: "Label", type: "string" },
      { key: "referencedAsset", label: "Referenced Asset", type: "string" },
    ],
    configFields: [
      { key: "text", label: "Text", type: "textarea", placeholder: "Use { } to reference upstream output", required: true },
    ],
  },
];

export const registry: Record<string, NodeDefinition> = Object.fromEntries(
  [...triggers, ...actions].map((n) => [n.id, n])
);
